### ISSUE TITLE
[BUG] - Cannot read properties of undefined (reading 'rows')

### ISSUE THREAD

**Issue by melohagan** [pixelinfinito/budibase-calendar#3]
Thanks for working on this calendar component!

I did try it out, but I wasn't able to get it working: 

<img width="1483" alt="Screenshot 2023-03-22 at 10 07 00" src="https://user-images.githubusercontent.com/101575380/226869854-e6fb04f7-94fa-4337-abc5-5066e8150d62.png">

**Comment by mctlisboa** [comment]
Hi @melohagan! I see on your screenshot that you haven’t mapped the title and date fields in the settings sidebar. Could you add the name of the column on your datasource that you would like to be the title of the event, and do the same for the date field? It is also currently necessary to refresh the page.

**Comment by melohagan** [comment]
@mctlisboa That works perfectly now. Brilliant plugin - great job! 🌟 🎸 

Might be worth adding a patch to gracefully handle that error nonetheless.
